<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>6e5afc4c-9bf8-4f77-a315-9e6bb68a7c87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapwrap']/header/nav/div[3]/div[5]/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.bmd-login-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>090de2cc-e051-486b-99fa-62c3903cf70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://accounts.bhinneka.com/login?returnUrl=https://www.bhinneka.com/</value>
      <webElementGuid>a2e380f9-7fff-4215-b82f-756a0fe63f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bmd-login-button</value>
      <webElementGuid>178e3f94-39ac-451d-803b-0a3d9e866e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Login
                    </value>
      <webElementGuid>48f2bafb-268b-45b1-ab81-7768076babde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapwrap&quot;)/header[1]/nav[@class=&quot;bmd-navbar&quot;]/div[@class=&quot;bmd-navbar-container container&quot;]/div[@class=&quot;bmd-header-account-wrapper&quot;]/span[@class=&quot;bmd-login-group&quot;]/a[@class=&quot;bmd-login-button&quot;]</value>
      <webElementGuid>260e5db9-587b-4b08-ad82-58d01bf51644</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapwrap']/header/nav/div[3]/div[5]/span/a</value>
      <webElementGuid>01a292c8-4550-4bfc-ad76-1f5ddddac29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>1d2060ba-d934-45fc-a8a8-9fa4d6c5bfa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::a[1]</value>
      <webElementGuid>dfc149bc-cadb-4093-8670-c526c9643e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk Terlaris'])[2]/preceding::a[3]</value>
      <webElementGuid>f424d8b7-c157-4866-bf0a-0ccb8addadc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perkakas Unggulan'])[2]/preceding::a[4]</value>
      <webElementGuid>91b3b1d0-2902-4994-801a-8fc88455346f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>1bebc36d-1b14-4dc5-961a-26d299bc3c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://accounts.bhinneka.com/login?returnUrl=https://www.bhinneka.com/')]</value>
      <webElementGuid>5e6e8931-1383-4213-92c4-2f38dbd7029a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>a1b1b033-7a91-4d8b-9224-4a395e8dcbc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://accounts.bhinneka.com/login?returnUrl=https://www.bhinneka.com/' and (text() = '
                        Login
                    ' or . = '
                        Login
                    ')]</value>
      <webElementGuid>0eec6c54-9ca2-408e-8cda-afed6e90d3a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
