<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>e3a1d30d-7cee-489c-ae40-84a7b6b4b986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ef82707-faff-4f35-ac73-e62e0a9c793c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>af44a24f-f8be-4745-9118-b5a7b4f3c36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af364794-9b25-42db-b5cf-4661c5a76b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>df84f636-e8d5-4810-892b-e4612b0983b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;css-zu8qh5&quot;]/div[@class=&quot;css-w7sfil&quot;]/div[@class=&quot;css-1t6ms5n&quot;]/div[@class=&quot;css-hfym42&quot;]/div[@class=&quot;tunggal-form-item css-sdwsc8&quot;]/div[@class=&quot;children-item&quot;]/div[1]/div[1]/div[@class=&quot;tunggal-input css-gw25jo&quot;]/div[@class=&quot;css-1w6v8a6&quot;]/input[1]</value>
      <webElementGuid>613601d7-8d88-4b7e-8276-63ab8925ed6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>caee8bad-ede6-4fc8-b204-d36883250310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9834e95a-2945-44a6-aa18-e0a78b9a2609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>baa55c4f-8565-4abe-b91f-0506f1dbc8af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
